name = "opencatd_worker"
main = "src/index.ts"
compatibility_date = "2023-03-30"
route = "xxxxxxxxxxx"
kv_namespaces = [{ binding = "OPENCAT_DB", id = "xxxxxxxxxxx" }]
vars = { OPENAI_DOMAIN = "https://api.openai.com" }
